### ISSUE TITLE
ANE

### ISSUE THREAD

**Issue by SlavomirDurej** [fokator/ANE-Samsung-In-App-Purchase#1]
Hello, any chance you could include a compiled ANE as well in your build folder?
Would be most grateful!

**Comment by fokator** [comment]
https://github.com/fokator/ANE-Samsung-In-App-Purchase/releases

**Comment by SlavomirDurej** [comment]
many thanks / vdaka!!

**Comment by SlavomirDurej** [comment]
I don't suppose you're going to upgrade this to IAP v.5 anytime soon :) ?
